host: khemenu.thoth-station.ninja
tls_verify: true
requirements_format: pip

runtime_environments:
  - name: 'rhel-8'
    operating_system:
      name: rhel
      version: "8.0"
    python_version: "3.8"
    recommendation_type: latest

managers:
  - name: info
  - name: version
    configuration:
      maintainers:
        - dralley
        - gerrod3
      assignees:
        - sesheta
      labels: [bot]
      changelog_file: false
      changelog_smart: false
